modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "immortalcombat"
version = "${version}"
displayName = "Immortal Combat"
authors = "GeradesoLukas, mohnbraten"
description = '''
Combat go brr
'''
#logoFile = ""

[[dependencies.immortalcombat]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immortalcombat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immortalcombat]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"